name: Build and Deploy Unity WebGL
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Unity WebGL
    runs-on: ubuntu-latest
    steps:
      # Checkout репозитория
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Кэширование Unity Library для ускорения сборки
      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Активация Unity Personal лицензии
      - name: Activate Unity License
        uses: game-ci/unity-activate@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          # Если 2FA включена, раскомментируй следующую строку:
          # UNITY_TOTP_KEY: ${{ secrets.UNITY_TOTP_KEY }}

      # Сборка проекта
      - name: Build project
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: WebGL
          unityVersion: 6000.0.33f1 # Указываем Unity 6.0
          buildPath: build/WebGL

      # Сохранение артефакта сборки
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: webgl-build
          path: build/WebGL

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Скачивание артефакта сборки
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: webgl-build
          path: build/WebGL

      # Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/WebGL
          publish_branch: gh-pages