name: Build and Deploy Unity WebGL
on:
  push:
    branches:
      - CICDAddressablesBuild  
jobs:
  build:
    name: Build Unity WebGL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL
          unityVersion: 6000.0.33f1
          buildsPath: WebGLBuild

      # Отладочный шаг: Показать структуру WebGLBuild
      - name: Debug WebGLBuild contents
        run: |
          echo "Contents of WebGLBuild:"
          find WebGLBuild -type f
