name: Build and Deploy Unity WebGL with Addressables

on:
  push:
    branches:
      - CICDAddressablesBuild

jobs:
  build:
    name: Build Unity WebGL
    runs-on: ubuntu-latest
    steps:
      # Проверка и выгрузка репозитория
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Кэширование Library для ускорения сборки
      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Проверка подключения к интернету и CCD
      - name: Test internet and CCD connectivity
        run: |
          ping -c 4 google.com
          curl -I https://b977e451-0a43-470b-a492-2393339bbas77.client-api.unity3dusercontent.com

      # Проверка профиля Addressables
      - name: Debug Addressables Profile
        run: |
          echo "Current Addressables profile:"
          find . -name "*.addressables" -exec cat {} \;

      # Сборка проекта
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL
          unityVersion: 6000.0.33f1
          buildsPath: WebGLBuild

      # Отладка: Показать структуру WebGLBuild
      - name: Debug WebGLBuild contents
        run: |
          echo "Contents of WebGLBuild:"
          find WebGLBuild -type f

      # Загрузка WebGL билда как артефакта
      - name: Upload WebGL Build
        uses: actions/upload-artifact@v4
        with:
          name: WebGL-Build
          path: WebGLBuild/
          retention-days: 30