name: Build and Deploy Unity WebGL
on:
  push:
    branches:
      - develop  
jobs:
  build:
    name: Build Unity WebGL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL
          unityVersion: 6000.0.33f1
          buildsPath: WebGLBuild
          buildName: WebGL

      # Отладочный шаг: Показать структуру WebGLBuild
      - name: Debug WebGLBuild contents
        run: |
          echo "Contents of build directory:"
          ls -la
          if [ -d "build" ]; then
            echo "Contents of build/:"
            find build -type f | head -20
          fi
          if [ -d "WebGLBuild" ]; then
            echo "Contents of WebGLBuild:"
            find WebGLBuild -type f | head -20
          else
            echo "WebGLBuild directory not found"
          fi

      # Перемещение файлов из build в WebGLBuild
      - name: Move build files
        run: |
          echo "=== ДИАГНОСТИКА СТРУКТУРЫ ==="
          echo "Полная структура WebGLBuild:"
          find WebGLBuild -type f | head -30
          echo ""
          
          # Проверяем разные варианты структуры
          if [ -d "WebGLBuild/WebGL/WebGL" ]; then
            echo "Found DOUBLE nested structure: WebGLBuild/WebGL/WebGL"
            # Исправляем права
            sudo chown -R runner:docker WebGLBuild/
            # Перемещаем из двойной вложенности
            cp -rf WebGLBuild/WebGL/WebGL/* WebGLBuild/
            rm -rf WebGLBuild/WebGL
            echo "Successfully moved from WebGLBuild/WebGL/WebGL/* to WebGLBuild/"
          elif [ -d "WebGLBuild/WebGL" ]; then
            echo "Found WebGLBuild/WebGL, copying contents to root"
            sudo chown -R runner:docker WebGLBuild/
            cp -rf WebGLBuild/WebGL/* WebGLBuild/
            rm -rf WebGLBuild/WebGL
            echo "Successfully moved WebGL build files"
          else
            echo "WebGLBuild structure not recognized!"
            echo "Available directories:"
            find WebGLBuild -type d | sort
          fi
          
          echo "=== РЕЗУЛЬТАТ ПЕРЕМЕЩЕНИЯ ==="
          echo "Содержимое WebGLBuild после перемещения:"
          find WebGLBuild -maxdepth 2 -type f | sort

      # Перемещение index.html и связанных файлов в корень
      - name: Prepare files for deployment
        run: |
          # Убеждаемся что права правильные
          sudo chown -R runner:docker WebGLBuild/ 2>/dev/null || true
          
          if [ -f WebGLBuild/index.html ]; then
            echo "index.html found in WebGLBuild root"
          else
            echo "index.html not found in root, searching in subdirectories..."
            found=$(find WebGLBuild -name "index.html" -type f)
            if [ -n "$found" ]; then
              echo "Found index.html at $found"
              mv $(dirname "$found")/* WebGLBuild/
              find WebGLBuild -type d -empty -delete
            else
              echo "Error: index.html not found in WebGLBuild"
              exit 1
            fi
          fi

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: webgl-build
          path: WebGLBuild

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: webgl-build
          path: WebGLBuild

      # Отладочный шаг: Показать структуру перед деплоем
      - name: Debug deploy contents
        run: |
          echo "Contents of WebGLBuild before deploy:"
          find WebGLBuild -type f

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.MULTICAST_TOKEN }}
          publish_dir: WebGLBuild
          publish_branch: gh-pages
